name: React CI/CD with Netlify & DockerHub

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (if any)
      - name: Run tests
        run: npm run test -- --watchAll=false

      # 5. Build React app
      - name: Build the app
        run: npm run build

      # 6. Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          npx netlify deploy --prod --dir=build \
          --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
          --site=${{ secrets.NETLIFY_SITE_ID }}

      # 7. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/recipedia:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/recipedia:latest
